// Copyright Asamoto.

#include "SIntroPanel.h"

#include "Widgets/SBoxPanel.h"
#include "Widgets/SOverlay.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Layout/SBorder.h"
#include "Widgets/Layout/SBox.h"
#include "Widgets/Layout/SScrollBox.h"
#include "Widgets/Text/STextBlock.h"
#include "Styling/CoreStyle.h"

namespace
{
	// Verbatim from introduction.md (markup stripped).
	const TCHAR* GIntroBody = TEXT(
		"(this text is generated by Human) ALL OF THIS WILL DEFINITELY BE CHANGED (especially textures)\n"
		"\n"
		"In this game you are trying to be a daimyo in feudal Japan (not really, but close)\n"
		"First you need to construct your city.\n"
		"To do so - select the desired item on the UI bar and place it with LMB, to cancel - press RMB.\n"
		"After you have villagers and buildings for work - assign villagers to specific building via "
		"UI interaction (top-right) (appears after building is placed.)\n"
		"Also, please don't mind similar textures for buildings....\n"
		"\n"
		"1. Start by placing a Warehouse, which stores food gathered by villagers as well as any "
		"construction materials or other gatherable resources.\n"
		"2. Next you can place a House, in which initially 1 villager lives. (future idea is to expand "
		"it to villager -> artisan(worker) -> samurai). He (or She, but probably He) is currently Idle "
		"and needs a workplace. After you assign them (again top-right corner) they would walk to "
		"their workplace, LOOK AT THEM CUBES GO! (ignore the debug text on top of their heads, "
		"pretty please)\n"
		"3. For that you place Lumberyard (preferably near the trees, so it's easier for workers to "
		"walk from the workplace to the chopping part)\n"
		"4. Next you need to place a Sawmill, which will process logs chopped in lumberyard (and "
		"carried to the warehouse) to planks (number is reflected on UI top-left)\n"
		"5. Additional you can place a  to generate food, which comes with a little farm "
		"field(not visible with current model), where workers do their job.\n"
		"6. Oh yes, villagers also starve (a little, maybe too much, it's just so that it happens fast "
		"for this demo purposes), so keep the farms going!\n"
		"7. In case you didn't notice there are some small tooltips on every building containing short "
		"explanation of what does this building do exactly (maybe not exactly, but yea...)\n"
		"8. Most important part - THE ROADS, try drawing them , curving them, combining with other "
		"roads, ROADS! For me, personally, it is very addicting. (Next idea is to attach buildings to "
		"the road and make villagers speed up while using it, so it should incentivize constructing "
		"proper roads)\n"
		"9, 10, 11... more buildings, more types of villagers, art, tech tree, trade, minigames(?)\n"
		"\n"
		"And after relaxed building-phase is done MAYBE IT'S TIME FOR WAR!\n"
		"\n"
		"For that I'm planning to do something like a 3rd-person commander role for the troops "
		"gathered from your village population (peasants, and in the future maybe samurai), similar "
		"to bannerlord or something adjacent. WOULD BE COOL, RIGHT!? right?...");
}

void SIntroPanel::Construct(const FArguments& InArgs)
{
	// The widget spans the whole viewport; only the panel itself (and its X
	// button / scrollbar) should catch the mouse, everything else falls
	// through to the world so the scene stays playable.
	SetVisibility(EVisibility::SelfHitTestInvisible);

	ChildSlot
	[
		SNew(SOverlay)

		+ SOverlay::Slot()
		.HAlign(HAlign_Left)
		.VAlign(VAlign_Top)
		.Padding(16.f, 64.f, 0.f, 0.f)   // sits just below the resource readout
		[
			SNew(SBox)
			.WidthOverride(528.f)
			.MaxDesiredHeight(672.f)
			[
				SNew(SBorder)
				.BorderImage(FCoreStyle::Get().GetBrush("WhiteBrush"))
				.BorderBackgroundColor(FLinearColor(0.f, 0.f, 0.f, 0.7f))
				.Padding(FMargin(12.f, 8.f))
				[
					SNew(SVerticalBox)

					// Title row with the close button.
					+ SVerticalBox::Slot()
					.AutoHeight()
					.Padding(0.f, 0.f, 0.f, 6.f)
					[
						SNew(SHorizontalBox)

						+ SHorizontalBox::Slot()
						.FillWidth(1.f)
						.VAlign(VAlign_Center)
						[
							SNew(STextBlock)
							.Font(FCoreStyle::GetDefaultFontStyle("Bold", 17))
							.ColorAndOpacity(FLinearColor(1.f, 0.85f, 0.4f))
							.Text(NSLOCTEXT("Realm", "IntroTitle", "Introduction"))
						]

						+ SHorizontalBox::Slot()
						.AutoWidth()
						.VAlign(VAlign_Top)
						[
							SNew(SButton)
							.ButtonColorAndOpacity(FLinearColor(1.f, 1.f, 1.f, 0.25f))
							.ContentPadding(FMargin(6.f, 1.f))
							.ToolTipText(NSLOCTEXT("Realm", "IntroCloseTip", "Close"))
							.OnClicked(this, &SIntroPanel::OnCloseClicked)
							[
								SNew(STextBlock)
								.Font(FCoreStyle::GetDefaultFontStyle("Bold", 13))
								.Text(NSLOCTEXT("Realm", "IntroClose", "X"))
							]
						]
					]

					+ SVerticalBox::Slot()
					.FillHeight(1.f)
					[
						SNew(SScrollBox)

						+ SScrollBox::Slot()
						[
							SNew(STextBlock)
							.Font(FCoreStyle::GetDefaultFontStyle("Regular", 12))
							.AutoWrapText(true)
							.Text(FText::FromString(GIntroBody))
						]
					]
				]
			]
		]
	];
}

FReply SIntroPanel::OnCloseClicked()
{
	// Collapse rather than remove: the controller still owns the widget and
	// cleans it up in EndPlay, so closing is a pure visual toggle.
	SetVisibility(EVisibility::Collapsed);
	return FReply::Handled();
}
