[/Script/Engine.GameUserSettings]
; 0=fullscreen, 1=windowed fullscreen, 2=windowed
FullscreenMode=2
LastConfirmedFullscreenMode=2
ResolutionSizeX=1600
ResolutionSizeY=900
LastUserConfirmedResolutionSizeX=1600
LastUserConfirmedResolutionSizeY=900
Version=5
